#!/usr/bin/env bash
# 1-install_nginx_web_server
# a Bash script that configures a new Ubuntu machine
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart 
